// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NatalCare.DataAccess.data;

#nullable disable

namespace NatalCare.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241101051437_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "223e5845-f58c-493f-b6b4-46ff3b18a332",
                            RoleId = "18ab63db-22b1-4656-93e8-6240c08c988c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("StatusCode")
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("CategoryId");

                    b.HasIndex("StatusCode");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Masters",
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3079),
                            StatusCode = "AC"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Patient Management",
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3082),
                            StatusCode = "AC"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Billing & Payement",
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3083),
                            StatusCode = "AC"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Reports",
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3084),
                            StatusCode = "AC"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Maintenance",
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3085),
                            StatusCode = "AC"
                        });
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Modules", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ModuleTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusCode")
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("ModuleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StatusCode");

                    b.ToTable("Module");

                    b.HasData(
                        new
                        {
                            ModuleId = 1,
                            CategoryId = 1,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3107),
                            ModuleTitle = "Dashboard",
                            StatusCode = "AC"
                        },
                        new
                        {
                            ModuleId = 2,
                            CategoryId = 2,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3110),
                            ModuleTitle = "Patient Records",
                            StatusCode = "AC"
                        },
                        new
                        {
                            ModuleId = 3,
                            CategoryId = 2,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3111),
                            ModuleTitle = "Newborn Records",
                            StatusCode = "AC"
                        },
                        new
                        {
                            ModuleId = 4,
                            CategoryId = 2,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3112),
                            ModuleTitle = "Admission / In-Patient",
                            StatusCode = "AC"
                        },
                        new
                        {
                            ModuleId = 5,
                            CategoryId = 2,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3113),
                            ModuleTitle = "Out-Patient (OPD)",
                            StatusCode = "AC"
                        },
                        new
                        {
                            ModuleId = 6,
                            CategoryId = 3,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3114),
                            ModuleTitle = "Invoice List",
                            StatusCode = "AC"
                        },
                        new
                        {
                            ModuleId = 7,
                            CategoryId = 3,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3115),
                            ModuleTitle = "Generate Invoice",
                            StatusCode = "AC"
                        },
                        new
                        {
                            ModuleId = 8,
                            CategoryId = 4,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3116),
                            ModuleTitle = "Natality Reports",
                            StatusCode = "AC"
                        },
                        new
                        {
                            ModuleId = 9,
                            CategoryId = 4,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3117),
                            ModuleTitle = "Invoice Reports",
                            StatusCode = "AC"
                        },
                        new
                        {
                            ModuleId = 10,
                            CategoryId = 5,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3118),
                            ModuleTitle = "Profiles",
                            StatusCode = "AC"
                        },
                        new
                        {
                            ModuleId = 11,
                            CategoryId = 5,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3119),
                            ModuleTitle = "Users",
                            StatusCode = "AC"
                        });
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Newborn", b =>
                {
                    b.Property<string>("NewbornID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("APGAR")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Circumference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly?>("DateofBirth")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Head")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NewbornCreatedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Created_By");

                    b.Property<string>("NewbornUpdatedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Updated_By");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusCode")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Temp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("TimeofBirth")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewbornID");

                    b.HasIndex("MotherID");

                    b.HasIndex("NewbornCreatedBy");

                    b.HasIndex("NewbornUpdatedBy");

                    b.HasIndex("StatusCode");

                    b.ToTable("Newborn");
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Patients", b =>
                {
                    b.Property<string>("PatientID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CivilStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Emergency_Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emergency_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasPhilHealth")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHIC_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientCreatedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Created_By");

                    b.Property<string>("PatientUpdatedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Updated_By");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusCode")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TeleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientID");

                    b.HasIndex("PatientCreatedBy");

                    b.HasIndex("PatientUpdatedBy");

                    b.HasIndex("StatusCode");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Prenatal", b =>
                {
                    b.Property<string>("CaseNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Abortion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateVisit")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EDC")
                        .HasColumnType("date");

                    b.Property<string>("Gravida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HRCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("LMP")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Para")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrenatalCreatedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Created_By");

                    b.Property<string>("PrenatalUpdatedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Updated_By");

                    b.Property<string>("StatusCode")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("StillBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("CaseNo");

                    b.HasIndex("PatientID");

                    b.HasIndex("PrenatalCreatedBy");

                    b.HasIndex("PrenatalUpdatedBy");

                    b.HasIndex("StatusCode");

                    b.ToTable("Prenatal");
                });

            modelBuilder.Entity("NatalCare.Models.Entities.PrenatalVisit", b =>
                {
                    b.Property<int>("PrenatalVisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrenatalVisitID"));

                    b.Property<string>("AOGWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateVisit")
                        .HasColumnType("datetime2");

                    b.Property<string>("FH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FHT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextVisit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfVisit")
                        .HasColumnType("int");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhysicalAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenatalCreatedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Created_By");

                    b.Property<string>("PrenatalUpdatedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Updated_By");

                    b.Property<string>("RR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusCode")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Temp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrenatalVisitID");

                    b.HasIndex("CaseNo");

                    b.HasIndex("PatientID");

                    b.HasIndex("PrenatalCreatedBy");

                    b.HasIndex("PrenatalUpdatedBy");

                    b.HasIndex("StatusCode");

                    b.ToTable("PrenatalVisit");
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Role_Access", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("OpenAccess")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("RoleId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("Role_access");

                    b.HasData(
                        new
                        {
                            RoleId = "18ab63db-22b1-4656-93e8-6240c08c988c",
                            ModuleId = 1,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3147),
                            OpenAccess = "Y"
                        },
                        new
                        {
                            RoleId = "18ab63db-22b1-4656-93e8-6240c08c988c",
                            ModuleId = 2,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3149),
                            OpenAccess = "Y"
                        },
                        new
                        {
                            RoleId = "18ab63db-22b1-4656-93e8-6240c08c988c",
                            ModuleId = 3,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3150),
                            OpenAccess = "Y"
                        },
                        new
                        {
                            RoleId = "18ab63db-22b1-4656-93e8-6240c08c988c",
                            ModuleId = 4,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3151),
                            OpenAccess = "Y"
                        },
                        new
                        {
                            RoleId = "18ab63db-22b1-4656-93e8-6240c08c988c",
                            ModuleId = 5,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3152),
                            OpenAccess = "Y"
                        },
                        new
                        {
                            RoleId = "18ab63db-22b1-4656-93e8-6240c08c988c",
                            ModuleId = 6,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3153),
                            OpenAccess = "Y"
                        },
                        new
                        {
                            RoleId = "18ab63db-22b1-4656-93e8-6240c08c988c",
                            ModuleId = 7,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3153),
                            OpenAccess = "Y"
                        },
                        new
                        {
                            RoleId = "18ab63db-22b1-4656-93e8-6240c08c988c",
                            ModuleId = 8,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3154),
                            OpenAccess = "Y"
                        },
                        new
                        {
                            RoleId = "18ab63db-22b1-4656-93e8-6240c08c988c",
                            ModuleId = 9,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3155),
                            OpenAccess = "Y"
                        },
                        new
                        {
                            RoleId = "18ab63db-22b1-4656-93e8-6240c08c988c",
                            ModuleId = 10,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3156),
                            OpenAccess = "Y"
                        },
                        new
                        {
                            RoleId = "18ab63db-22b1-4656-93e8-6240c08c988c",
                            ModuleId = 11,
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3158),
                            OpenAccess = "Y"
                        });
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Status", b =>
                {
                    b.Property<string>("StatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusCode");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            StatusCode = "AC",
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3057),
                            StatusName = "ACTIVE"
                        },
                        new
                        {
                            StatusCode = "IN",
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(3059),
                            StatusName = "INACTTIVE"
                        });
                });

            modelBuilder.Entity("NatalCare.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusCode")
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("StatusCode");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "223e5845-f58c-493f-b6b4-46ff3b18a332",
                            AccessFailedCount = 0,
                            Address = "Mabolo Cebu City",
                            Birthdate = new DateOnly(1952, 6, 7),
                            ConcurrencyStamp = "035ccf9c-2337-4575-99af-795fac9481cd",
                            Email = "lisa@paanakan.com",
                            EmailConfirmed = false,
                            FirstName = "lisa",
                            Gender = "Female",
                            LastName = "pdeuciano",
                            LockoutEnabled = true,
                            MiddleName = "valiz",
                            NormalizedEmail = "LISA@PAANAKAN.COM",
                            NormalizedUserName = "LISA",
                            PasswordHash = "AQAAAAIAAYagAAAAEGyjgIyp14MszGz90Bkg/ySJenVsZL6A3jIS+/4y71OtVSvfM3TmPBf/I3ff0iGhqw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "RHHJPIOEKQH4HWQZLCOLOYY4E5RMLV2T",
                            StatusCode = "AC",
                            TwoFactorEnabled = false,
                            UserName = "lisa"
                        });
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<DateTime?>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleCreatedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Created_By");

                    b.Property<string>("RoleUpdatedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Updated_By");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasIndex("RoleCreatedBy");

                    b.HasIndex("RoleUpdatedBy");

                    b.HasDiscriminator().HasValue("Role");

                    b.HasData(
                        new
                        {
                            Id = "18ab63db-22b1-4656-93e8-6240c08c988c",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Created_At = new DateTime(2024, 11, 1, 13, 14, 37, 169, DateTimeKind.Local).AddTicks(2981),
                            Description = "CRUD Anything",
                            RoleCreatedBy = "223e5845-f58c-493f-b6b4-46ff3b18a332"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NatalCare.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NatalCare.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatalCare.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NatalCare.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Category", b =>
                {
                    b.HasOne("NatalCare.Models.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Modules", b =>
                {
                    b.HasOne("NatalCare.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("NatalCare.Models.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode");

                    b.Navigation("Category");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Newborn", b =>
                {
                    b.HasOne("NatalCare.Models.Entities.Patients", "Patient")
                        .WithMany()
                        .HasForeignKey("MotherID");

                    b.HasOne("NatalCare.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("NewbornCreatedBy");

                    b.HasOne("NatalCare.Models.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("NewbornUpdatedBy");

                    b.HasOne("NatalCare.Models.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode");

                    b.Navigation("CreatedBy");

                    b.Navigation("Patient");

                    b.Navigation("Status");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Patients", b =>
                {
                    b.HasOne("NatalCare.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("PatientCreatedBy");

                    b.HasOne("NatalCare.Models.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("PatientUpdatedBy");

                    b.HasOne("NatalCare.Models.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode");

                    b.Navigation("CreatedBy");

                    b.Navigation("Status");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Prenatal", b =>
                {
                    b.HasOne("NatalCare.Models.Entities.Patients", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatalCare.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("PrenatalCreatedBy");

                    b.HasOne("NatalCare.Models.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("PrenatalUpdatedBy");

                    b.HasOne("NatalCare.Models.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode");

                    b.Navigation("CreatedBy");

                    b.Navigation("Patient");

                    b.Navigation("Status");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("NatalCare.Models.Entities.PrenatalVisit", b =>
                {
                    b.HasOne("NatalCare.Models.Entities.Prenatal", "PrenatalCase")
                        .WithMany()
                        .HasForeignKey("CaseNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatalCare.Models.Entities.Patients", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatalCare.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("PrenatalCreatedBy");

                    b.HasOne("NatalCare.Models.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("PrenatalUpdatedBy");

                    b.HasOne("NatalCare.Models.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode");

                    b.Navigation("CreatedBy");

                    b.Navigation("Patient");

                    b.Navigation("PrenatalCase");

                    b.Navigation("Status");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Role_Access", b =>
                {
                    b.HasOne("NatalCare.Models.Entities.Modules", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatalCare.Models.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NatalCare.Models.Entities.User", b =>
                {
                    b.HasOne("NatalCare.Models.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("NatalCare.Models.Entities.Role", b =>
                {
                    b.HasOne("NatalCare.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("RoleCreatedBy");

                    b.HasOne("NatalCare.Models.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("RoleUpdatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
